FROM jupyter/pyspark-notebook
RUN mkdir /home/jovyan/work/uploads
RUN chmod 777 /home/jovyan/work/uploads
#RUN pip install jupyter_contrib_nbextensions
#RUN jupyter contrib nbextension install --user
#RUN pip install jupyter_nbextensions_configurator
#RUN jupyter nbextensions_configurator enable --user
