FROM bde2020/hbase-standalone:1.0.0-hbase1.2.6

#RUN echo "create 'hbase:labels', 'f'" | hbase shell -n
#RUN echo "create 'water_meters',{NAME => 'basic'},{NAME => 'reading'},{NAME => 'location'}" | hbase shell -n
#RUN apt-get update
#RUN apt-get install inotify-tools -y
#RUN mkdir /uploads
